package entity;

// Generated 2015/5/15 ¤U¤È 03:10:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SshMasterTable generated by hbm2java
 */
@Entity
@Table(name = "SSH_MASTER_TABLE", schema = "PUBLIC", catalog = "PUBLIC")
public class SshMasterTable implements java.io.Serializable {

	private String guid;
	private Date createDate;

	public SshMasterTable() {
	}

	public SshMasterTable(String guid) {
		this.guid = guid;
	}

	public SshMasterTable(String guid, Date createDate) {
		this.guid = guid;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "GUID", unique = true, nullable = false, length = 20)
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
